version: '3.1'

services:
  springboot:
    image: mdzubair9908/springboot:test
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - 8080:8080
    networks:
    - springappnetwork  
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    driver: local
    
networks:
  springappnetwork:
    driver: bridge
